### ISSUE TITLE
Paper request

### ISSUE THREAD

**Issue by qian26** [thunlp/LEAD#1]
Hello, can you give the ArXiv link of paper? I can't find this paper either in Google scholar or on the EMNLP2024 website. Thanks.

**Comment by ggaoch** [comment]
Now it's on Arxiv! ^_^
https://arxiv.org/abs/2410.06581

**Comment by ggaoch** [comment]
> Hello, can you give the ArXiv link of paper? I can't find this paper either in Google scholar or on the EMNLP2024 website. Thanks.

Now it's on Arxiv! ^_^
https://arxiv.org/abs/2410.06581
