### ISSUE TITLE
Excuse me but how can you extract ac

### ISSUE THREAD

**Issue by Ciao-CA** [thunlp/LEAD#2]
![image](https://github.com/user-attachments/assets/feb87897-00bb-43b2-aff1-dab64510b21b)
I have noticed that you can extract main article and ancillary article, could you please tell me how can you make it, LLM or regular expression?

**Comment by ggaoch** [comment]
It's just regular expression. In chinese cases, we just need to extract the Chinese number characters ("一二三四...") in "Reason".

As for how to distinguish Main article and Ancillary article,  we simply categorize all articles with an entry number greater than or equal to 102 as 'Main Articles", and those with a entry number less than 102 as "Ancillary Articles" as _Criminal Law of China_ has such a boundary.

**Comment by Ciao-CA** [comment]
Thank you very much!
